name: dart_lab
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
publish_to: none

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  path: ^1.8.0
  dart_code_metrics: ^5.7.3
  equatable: ^2.0.5

dev_dependencies:
  lint: ^2.0.1
  lints: ^2.0.0
  test: ^1.21.0
